module.exports = {
  rules: {
    // '@typescript-eslint/quotes': 'off',
    // '@typescript-eslint/brace-style': 'off',
    // '@typescript-eslint/comma-dangle': 'off',
    // '@typescript-eslint/comma-spacing': 'off',
    // '@typescript-eslint/func-call-spacing': 'off',
    // '@typescript-eslint/keyword-spacing': 'off',
    // '@typescript-eslint/member-delimiter-style': 'off',
    // '@typescript-eslint/no-extra-parens': 'off',
    // '@typescript-eslint/no-extra-semi': 'off',
    // '@typescript-eslint/semi': 'off',
    // '@typescript-eslint/space-before-function-paren': 'off',
    // '@typescript-eslint/space-infix-ops': 'off',
    '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', ignoreRestSiblings: true }],
    '@typescript-eslint/ban-types': 'off',
    '@typescript-eslint/indent': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': ['error', { ignoreRestArgs: true }],
    '@typescript-eslint/no-empty-function': 'warn',
    '@typescript-eslint/no-use-before-define': [
      'warn',
      {
        functions: false,
        classes: false,
        variables: false,
        typedefs: false,
      },
    ],
    'no-unused-vars': 'off',
    'no-explicit-any': 'off',
    'no-empty-function': 'off',
    'no-use-before-define': 'off',
  },
};

//'@typescript-eslint/adjacent-overload-signatures': 'error',
//'@typescript-eslint/ban-ts-comment': 'error',
//'@typescript-eslint/ban-types': 'error',
//'@typescript-eslint/explicit-module-boundary-types': 'warn',
//'no-array-constructor': 'off',
//'@typescript-eslint/no-array-constructor': 'error',
//'no-empty-function': 'off',
//'@typescript-eslint/no-empty-function': 'error',
//'@typescript-eslint/no-empty-interface': 'error',
//'@typescript-eslint/no-explicit-any': 'warn',
//'@typescript-eslint/no-extra-non-null-assertion': 'error',
//'no-extra-semi': 'off',
//'@typescript-eslint/no-extra-semi': 'error',
//'@typescript-eslint/no-inferrable-types': 'error',
//'@typescript-eslint/no-misused-new': 'error',
//'@typescript-eslint/no-namespace': 'error',
//'@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
//'@typescript-eslint/no-non-null-assertion': 'warn',
//'@typescript-eslint/no-this-alias': 'error',
//'no-unused-vars': 'off',
//'@typescript-eslint/no-unused-vars': 'warn',
//'@typescript-eslint/no-var-requires': 'error',
//'@typescript-eslint/prefer-as-const': 'error',
//'@typescript-eslint/prefer-namespace-keyword': 'error',
//'@typescript-eslint/triple-slash-reference': 'error',
