module.exports = {
  rules: {
    // '@typescript-eslint/quotes': 'off',
    // '@typescript-eslint/brace-style': 'off',
    // '@typescript-eslint/comma-dangle': 'off',
    // '@typescript-eslint/comma-spacing': 'off',
    // '@typescript-eslint/func-call-spacing': 'off',
    // '@typescript-eslint/keyword-spacing': 'off',
    // '@typescript-eslint/member-delimiter-style': 'off',
    // '@typescript-eslint/no-extra-parens': 'off',
    // '@typescript-eslint/no-extra-semi': 'off',
    // '@typescript-eslint/semi': 'off',
    // '@typescript-eslint/space-before-function-paren': 'off',
    // '@typescript-eslint/space-infix-ops': 'off',
    // '@typescript-eslint/type-annotation-spacing': 'off',
    '@typescript-eslint/indent': 'error',
    '@typescript-eslint/no-var-requires': 'off',
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  },
};